[package]
name = "for_test_dove_repositories"
dialect = "pont"

dependencies = [
    { git = "https://github.com/pontem-network/move-stdlib", tag = "v0.1.2" },
    { git = "https://github.com/vladimirovmm/for_test_dove_repositories", branch="cyclic_dependency" }
]
